Update install configuration
- Install Homebrew
- Install Oh-my-zsh
- Init Lucario Terminal.app theme
- Cleanup desktop by using chflags to hide non-dot files

diff --git a/install b/install
--- a/install
+++ b/install
@@ -15,4 +15,57 @@ do
 	/bin/ln -fs ~/Desktop/${i} ~/${i}
 done
 
+# Homebrew
+/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+/usr/local/bin/brew tap caskroom/cask # https://caskroom.github.io/
+/usr/local/bin/brew install tmux
+
+# Oh-my-zsh
+/usr/bin/curl -#L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sudo bash
+
+# Terminal Theme
+defaults read com.apple.Terminal | grep lucario
+if [ $? != 0 ]; then
+defaults write com.apple.Terminal "Default Window Settings" "lucario"
+defaults write com.apple.Terminal "Startup Window Settings" "lucario"
+osascript <<EOD
+tell application "Terminal"
+  local allOpenedWindows
+  local initialOpenedWindows
+  local windowID
+  set themeName to "lucario"
+  (* Store the IDs of all the open terminal windows. *)
+  set initialOpenedWindows to id of every window
+  (* Open the custom theme so that it gets added to the list
+     of available terminal themes (note: this will open two
+     additional terminal windows). *)
+  do shell script "open '~/Desktop/" & themeName & ".terminal'"
+  (* Wait a little bit to ensure that the custom theme is added. *)
+  delay 1
+  (* Set the custom theme as the default terminal theme. *)
+  set default settings to settings set themeName
+  (* Get the IDs of all the currently opened terminal windows. *)
+  set allOpenedWindows to id of every window
+  repeat with windowID in allOpenedWindows
+    (* Close the additional windows that were opened in order
+       to add the custom theme to the list of terminal themes. *)
+    if initialOpenedWindows does not contain windowID then
+      close (every window whose id is windowID)
+    (* Change the theme for the initial opened terminal windows
+       to remove the need to close them in order for the custom
+       theme to be applied. *)
+    else
+      set current settings of tabs of (every window whose id is windowID) to settings set themeName
+    end if
+  end repeat
+end tell
+EOD
+fi
+
+# Chflags cleanup desktop
+for i in "install" "lucario.terminal" "README.md" "vscode.code-workspace"
+do
+	/usr/bin/chflags -h hidden ~/Desktop/${i}
+done
+
 exit 0
